application: oxylane-plus
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/admin
  static_dir: static/admin
  expiration: '0'

- url: /public
  static_dir: public
  expiration: '0'

- url: /
  script: main.application
  login: required

libraries:
- name: pycrypto
  version: "2.6"
- name: django
  version: "1.4"
- name: jinja2
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'socialplus.settings'

builtins:
- django_wsgi: on